apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "yourpassword"  # Use a secure password here
            - name: MYSQL_DATABASE
              value: "ghost"
            - name: MYSQL_USER
              value: "ghostuser"
            - name: MYSQL_PASSWORD
              value: "ghostpassword"  # Use a secure password here
