apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for MySQL to be ready..."
              while ! nc -z db 3306; do
                sleep 2
              done
              echo "MySQL is up, starting Ghost!"
      containers:
        - name: ghost
          image: ghost:5
          ports:
            - containerPort: 2368
          env:
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: "db"
            - name: database__connection__user
              value: "ghostuser"
            - name: database__connection__password
              value: "ghostpassword"
            - name: database__connection__database
              value: "ghost"
